name: magic
env:
  NODE_ENV: production
  PORT: 3000
services:
  web:
    image: railwayapp/start-web:0.11.1
    env:
      NODE_ENV: $NODE_ENV
      PORT: $PORT
    http:
      3000: 3000
    healthcheck:
      path: /